### ISSUE TITLE
Azure keyvault support

### ISSUE THREAD

**Issue by Nighthawk22** [zerok/tpl#19]
Hello,

Would be awesome to support secrets from Azure keyvault. 
Will most probably be implemented by us.

Thanks

**Comment by zerok** [comment]
Hm... sounds fun :) For when would you have that scheduled? If it doesn't have a high priority, I might be able to work on that too :)

**Comment by Nighthawk22** [comment]
Most probably in the next 2 sprints (4 weeks).
The idea would also be (depending on the possibility) to use that with the current vault layout but change the vault with an environment flag.

**Comment by zerok** [comment]
Sadly, it won't be that easy since Key Vault does not support / and secret names 😞 Looking at the API, the ID of a secret has to follow this pattern: `^[0-9a-zA-Z-]+$`
