### ISSUE TITLE
crash on wrong azure token usage

### ISSUE THREAD

**Issue by kautsig** [zerok/tpl#22]
I accidentally used a wrong input as token, the tool crashes with `invalid memory address or nil pointer dereference`.

Even though this is incorrect usage, I think we should never crash like this.

How to reproduce:

```
$ export AZURE_KEY_VAULT_URL=https://vaulturl

$ export AZURE_TOKEN=`az account get-access-token --resource https://vault.azure.net`

$ cat file.tpl
{{ .Azure.Secret "secrets--path" \| jsonToMap \| jmsepathValue "nested.json" }}

$ tpl ./file.tpl
FATA[0000] Failed to render                              error="template: ROOT:1:9: executing \"ROOT\" at <.Azure.Secret>: error calling Secret: runtime error: invalid memory address or nil pointer dereference"
```

Our process was super messy to get azure keyvault change in. I think we should not bother @zerok for releasing, when we're not 100% sure the result is what we want.

Pinging @vajura

**Comment by zerok** [comment]
The only possible nil there I could find so far was a missing logger. Can you please try your case with 56e88ee0c3f7cc79106ac5b8cc0cde588c1ba84d ? Thanks :)

**Comment by vajura** [comment]
Shouldnt be the logger, i will take a look and write up prettier error messages.

**Comment by kautsig** [comment]
I could not reproduce this on 4.2 any more, closing.
